name: "CD pipeline"

on:
  workflow_run:
    workflows: ["sample react CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v5
        with:
          node-version: "21"

      - name: "Install Vercel CLI"
        run: npm i -g vercel@latest

      - name: "Download build artifact"
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdProject
